kubeVersion: ">=1.24.0-0"
apiVersion: v2
name: forgejo
version: 1.0.5
appVersion: "1.20.4"
description: Self hosted GIT repositories
home: https://github.com/chadweimer/charts/charts/forgejo
icon: https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/assets/logo.svg
deprecated: false
dependencies:
  - name: common
    version: 14.3.5
    repository: https://library-charts.truecharts.org
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: memcached
    version: 6.0.77
    repository: https://deps.truecharts.org/
    condition: memcached.enabled
    alias: ""
    tags: []
    import-values: []
keywords:
  - git
  - issue tracker
  - code review
  - wiki
  - gitea
  - gogs
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/gitea
  - https://gitea.com/gitea/helm-chart
  - https://codeberg.org/forgejo/forgejo
  - https://codeberg.org/forgejo/-/packages/container/forgejo
type: application
